-- Generated by tools/stagerig_spec.py - do not edit by hand.
-- Edit stagerig/substitutions.json and regenerate instead.
return {
  concert = "NSM Tribute Night.concert",
  patches = {
    {
      name = "PIANO_ARENA",
      path = "PIANO_ARENA",
      colour = { 138, 92, 240 },
      tempo = 120.0,
      tracks = {
        { name = "Piano Arena — Splendid Grand", fx = "Pianoteq 8", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "GOSPEL_ORGAN",
      path = "GOSPEL_ORGAN",
      colour = { 62, 201, 192 },
      tempo = 120.0,
      tracks = {
        { name = "Gospel Organ — Rock Organ", fx = "B-3 V2", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "MELLOTRON_PSYCH",
      path = "MELLOTRON_PSYCH",
      colour = { 84, 208, 122 },
      tempo = 120.0,
      tracks = {
        { name = "Mellotron Psych — MkII Flute", fx = "SOLO", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "DX_EP_80S",
      path = "DX_EP_80S",
      colour = { 232, 178, 58 },
      tempo = 120.0,
      tracks = {
        { name = "DX EP 80S — Dexed", fx = "Dexed", kind = "exact", was = "Dexed" },
      },
    },
    {
      name = "RHODES_SOUL",
      path = "RHODES_SOUL",
      colour = { 224, 69, 90 },
      tempo = 120.0,
      tracks = {
        { name = "Rhodes Soul — Rhodes", fx = "Pianoteq 8", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "ORCH_HIT",
      path = "ORCH_HIT",
      colour = { 91, 157, 245 },
      tempo = 120.0,
      tracks = {
        { name = "Orch Hit — Firebird", fx = "BBC Symphony Orchestra", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "SPACE_PAD",
      path = "SPACE_PAD",
      colour = { 138, 92, 240 },
      tempo = 120.0,
      tracks = {
        { name = "Space Pad — Sweep Pad", fx = "Omnisphere", kind = "substituted", was = "(none detected)" },
      },
    },
    {
      name = "LEAD_MONO",
      path = "LEAD_MONO",
      colour = { 62, 201, 192 },
      tempo = 120.0,
      tracks = {
        { name = "Lead Mono — Snarling Pig", fx = "Omnisphere", kind = "substituted", was = "(none detected)" },
      },
    },
  },
}
