-- Generated by tools/stagerig_spec.py - do not edit by hand.
-- Edit stagerig/substitutions.json and regenerate instead.
return {
  concert = "Lagori 2026 Minimal.concert",
  patches = {
    {
      name = "Aasma",
      path = "Darbari / Aasma",
      colour = { 138, 92, 240 },
      tempo = 120.0,
      tracks = {
        { name = "Synth", fx = "Omnisphere", kind = "substituted", was = "Alchemy" },
        { name = "Strings", fx = "BBC Symphony Orchestra", kind = "substituted", was = "Sampler" },
        { name = "Full Strings", fx = "BBC Symphony Orchestra", kind = "substituted", was = "Sampler" },
        { name = "Cellos", fx = "BBC Symphony Orchestra", kind = "substituted", was = "Sampler" },
        { name = "Violas Staccato", fx = "BBC Symphony Orchestra", kind = "substituted", was = "Sampler" },
        { name = "Synth", fx = "Omnisphere", kind = "substituted", was = "Alchemy" },
        { name = "ORCH", fx = "BBC Symphony Orchestra", kind = "substituted", was = "(none detected)" },
        { name = "Piano", fx = "Pianoteq 8", kind = "exact", was = "Pianoteq 8" },
      },
    },
    {
      name = "Humma Humma G -> A",
      path = "Darbari / Humma Humma G -> A",
      colour = { 62, 201, 192 },
      tempo = 110.0,
      tracks = {
        { name = "Horn", fx = "Kontakt 7", kind = "substituted", was = "Sampler" },
        { name = "Horns High", fx = "Kontakt 7", kind = "substituted", was = "Sampler" },
        { name = "Organ", fx = "Omnisphere", kind = "substituted", was = "Vintage B3" },
      },
    },
    {
      name = "BRAHMA Gm",
      path = "60 90 / BRAHMA Gm",
      colour = { 84, 208, 122 },
      tempo = 118.0,
      tracks = {
        { name = "Inst 39", fx = "Omnisphere", kind = "substituted", was = "Vintage B3" },
        { name = "Clav", fx = "Pianoteq 8", kind = "exact", was = "Pianoteq 8" },
      },
    },
    {
      name = "Upright",
      path = "Darbari / Upright",
      colour = { 232, 178, 58 },
      tempo = 115.0,
      tracks = {
        { name = "Piano", fx = "Pianoteq 8", kind = "exact", was = "Pianoteq 8" },
      },
    },
    {
      name = "Maari Kannu",
      path = "Maari Kannu / Maari Kannu",
      colour = { 224, 69, 90 },
      tempo = 106.0,
      tracks = {
        { name = "Grand Organ", fx = "Omnisphere", kind = "substituted", was = "Vintage B3" },
        { name = "Clav", fx = "Pianoteq 8", kind = "exact", was = "Pianoteq 8" },
        { name = "Horn Section", fx = "Kontakt 7", kind = "substituted", was = "Sampler + Studio Horns" },
        { name = "Horn Section", fx = "Kontakt 7", kind = "substituted", was = "Sampler + Studio Horns" },
      },
    },
  },
}
