-- @description StageRig Build
-- @version 0.1.0
-- @author Jason Zac
-- @link https://github.com/jasonzacmusic/nathaniel-tools
-- @donation https://github.com/jasonzacmusic/nathaniel-tools
-- @about
--   Requires the "Shared Libraries" package from this same repository.
--   ReaPack has no automatic dependencies, so install that one too - or just
--   right-click the repository in ReaPack and choose Install All.
--   Builds a live concert project from a rig spec generated out of a MainStage
--   .concert file. Creates one folder per patch, one track per channel strip,
--   inserts the substitute instrument where one is known, and puts the note
--   tracker in front of every instrument so patch switching can be clean.
-- @changelog
--   0.1.0 - first version. Five-patch Lagori rig.

--[[
  StageRig Build
  ----------------------------------------------------------------------------
  Reads stagerig/rig.lua (generated by tools/stagerig_spec.py) and builds the
  concert project.

  ARCHITECTURE, per docs/TECH_BRIEF.md §7 - these are decided, not open:
    - one REAPER project = one concert; patches are folder tracks
    - everything that will ever make sound is instantiated HERE, at build time.
      Nothing is created, destroyed or reconfigured once the set has started.
    - the setlist lives in project ExtState, decoupled from the timeline
    - the note tracker sits at the TOP of every instrument chain, so the gate
      is in front of the instrument rather than after it

  This script BUILDS. It does not switch. Switching is StageRig.lua's job.

  It refuses to run on a project that already has tracks, so it can never
  bulldoze a session you had open.
--]]

local r = reaper
local SCRIPT_DIR = ({r.get_action_context()})[2]:match("(.*[/\\])")
package.path = SCRIPT_DIR .. "lib/?.lua;" .. package.path

local okSafe, safe = pcall(require, "nt_safe")
if not okSafe then
  r.ShowMessageBox("Could not load scripts/lib/nt_safe.lua.\n\n" .. tostring(safe),
    "StageRig Build", 0)
  return
end

local EXT = "NT_STAGERIG"

--------------------------------------------------------------------------------
-- locate the rig spec
--------------------------------------------------------------------------------

local function findSpec()
  local candidates = {
    SCRIPT_DIR .. "../stagerig/rig.lua",
    SCRIPT_DIR .. "stagerig/rig.lua",
    r.GetResourcePath() .. "/Scripts/Nathaniel Tools/stagerig/rig.lua",
  }
  for _, p in ipairs(candidates) do
    local f = io.open(p, "r")
    if f then f:close(); return p end
  end
  return nil
end

local specPath = findSpec()
if not specPath then
  r.ShowMessageBox(
    "No rig spec found.\n\nGenerate one first:\n" ..
    "  tools/stagerig_spec.py <concert> --patches ... --out stagerig/rig.json\n\n" ..
    "It writes rig.lua alongside rig.json, which is what this script reads.",
    "StageRig Build", 0)
  return
end

local okSpec, RIG = pcall(dofile, specPath)
if not okSpec or type(RIG) ~= "table" or not RIG.patches then
  r.ShowMessageBox("The rig spec would not load:\n\n" .. tostring(RIG),
    "StageRig Build", 0)
  return
end

--------------------------------------------------------------------------------
-- guards
--------------------------------------------------------------------------------

local proj = 0
if r.CountTracks(proj) > 0 then
  local ok = r.ShowMessageBox(
    "This project already has " .. r.CountTracks(proj) .. " tracks.\n\n" ..
    "StageRig Build is meant to run into an EMPTY project so it can never " ..
    "damage a session.\n\nOpen a new project tab and run it there.",
    "StageRig Build", 0)
  return
end

--------------------------------------------------------------------------------
-- helpers
--------------------------------------------------------------------------------

local function nativeColour(rgb)
  return r.ColorToNative(rgb[1], rgb[2], rgb[3]) | 0x1000000
end

local function addTrack(idx, name, colour)
  r.InsertTrackAtIndex(idx, false)
  local t = r.GetTrack(proj, idx)
  if not t then return nil end
  r.GetSetMediaTrackInfo_String(t, "P_NAME", name, true)
  if colour then r.SetMediaTrackInfo_Value(t, "I_CUSTOMCOLOR", nativeColour(colour)) end
  return t
end

-- Insert an FX by name and report honestly whether it actually landed.
-- TrackFX_AddByName returns -1 when the plugin is not installed; we do NOT
-- want that to look like success, because a silently empty instrument track is
-- exactly the kind of thing that is only discovered on stage.
-- Try the plain name first, then each format prefix. Probed on this machine:
-- every instrument REAPER can actually instantiate resolves by plain name
-- (Pianoteq 8, Omnisphere, BBC Symphony Orchestra, Kontakt 7, SOLO, ANA 2,
-- Keyscape, and JS effects alike), so the prefixes are belt-and-braces for
-- other machines rather than the fix for anything seen here.
--
-- When a name fails under EVERY form, the plugin genuinely cannot be loaded -
-- it is scanned-but-unauthorised, or missing. Saying "not installed" is then
-- the honest report, and the track is left named and routed but silent rather
-- than quietly given some other sound.
local FX_PREFIXES = { "", "AU: ", "AUi: ", "VST3i: ", "VST3: ", "VSTi: ", "VST: ", "JS: " }

local function addFX(track, fxName)
  if not fxName then return false, "no instrument chosen" end
  for _, pre in ipairs(FX_PREFIXES) do
    local idx = r.TrackFX_AddByName(track, pre .. fxName, false, -1)
    if idx and idx >= 0 then return true, nil end
  end
  return false, "not installed under any format prefix: " .. fxName
end

local log = {}
local function say(s) log[#log+1] = s end

--------------------------------------------------------------------------------
-- build
--------------------------------------------------------------------------------

r.Undo_BeginBlock2(proj)
r.PreventUIRefresh(1)

local idx = 0
local setlist = {}
local problems = 0

for pi, patch in ipairs(RIG.patches) do
  local folder = addTrack(idx, patch.name, patch.colour)
  if folder then
    -- folder parent
    r.SetMediaTrackInfo_Value(folder, "I_FOLDERDEPTH", 1)
    -- every patch starts muted; StageRig unmutes the first one when the set loads
    r.SetMediaTrackInfo_Value(folder, "B_MUTE", 1)
    idx = idx + 1

    local guids = {}
    for ti, trk in ipairs(patch.tracks) do
      local t = addTrack(idx, trk.name, patch.colour)
      if t then
        -- The note tracker goes in FIRST, so it sits in front of the
        -- instrument and its gate actually stops notes reaching it.
        local okGate = addFX(t, "nt_note_tracker")
        if not okGate then
          problems = problems + 1
          say("  ! note tracker missing on " .. patch.name .. " / " .. trk.name)
        end

        local okFx, err = addFX(t, trk.fx)
        if not okFx then
          problems = problems + 1
          say(("  ! %s / %s  ->  %s"):format(patch.name, trk.name, err))
        end

        -- Live input: this MIDI keyboard, all channels, monitoring on. Record
        -- arm stays OFF - monitoring is what makes it audible, arming is what
        -- makes it record, and nothing on stage should be armed by accident.
        r.SetMediaTrackInfo_Value(t, "I_RECINPUT", 4096 | (63 << 5))
        r.SetMediaTrackInfo_Value(t, "I_RECMON", 1)
        r.SetMediaTrackInfo_Value(t, "I_RECARM", 0)

        -- Mute the child too, not just the folder. Muting the parent alone does
        -- silence the patch, but StageRig mutes and unmutes folder AND children
        -- together - so if the build leaves children unmuted the two disagree
        -- about the starting state, and the first switch behaves differently
        -- from every one after it.
        r.SetMediaTrackInfo_Value(t, "B_MUTE", 1)

        -- last child closes the folder
        if ti == #patch.tracks then
          r.SetMediaTrackInfo_Value(t, "I_FOLDERDEPTH", -1)
        end

        guids[#guids+1] = r.GetTrackGUID(t)
        idx = idx + 1
      end
    end

    setlist[#setlist+1] = {
      name = patch.name,
      folder = r.GetTrackGUID(folder),
      tracks = guids,
      tempo = patch.tempo,
    }
    say(("%d. %s  (%d tracks)"):format(pi, patch.name, #guids))
  end
end

-- Folder arithmetic must be well-formed by construction, but prove it anyway.
local fixes = safe.normaliseFolders(proj)
if fixes > 0 then say(("(repaired %d folder depths)"):format(fixes)) end

--------------------------------------------------------------------------------
-- the setlist lives in ExtState, not in the timeline
--------------------------------------------------------------------------------

local ser = {}
for i, p in ipairs(setlist) do
  ser[#ser+1] = table.concat({
    i, p.name, p.folder, p.tempo or 0, table.concat(p.tracks, ",")
  }, "\31")
end
r.SetProjExtState(proj, EXT, "setlist", table.concat(ser, "\30"))
r.SetProjExtState(proj, EXT, "concert", RIG.concert or "")
r.SetProjExtState(proj, EXT, "version", "0.1.0")

r.PreventUIRefresh(-1)
r.TrackList_AdjustWindows(false)
r.UpdateArrange()
r.Undo_EndBlock2(proj, "StageRig: build concert", -1)

--------------------------------------------------------------------------------
-- report - including, especially, what did NOT work
--------------------------------------------------------------------------------

local head = ("StageRig built %d patches, %d tracks, from:\n%s\n\n")
  :format(#setlist, idx, RIG.concert or "?")

local tail
if problems == 0 then
  tail = "\nEvery track got its instrument.\n"
else
  tail = ("\n%d track(s) have no instrument loaded - they are created, named " ..
    "and routed, but silent until you drop something in.\n"):format(problems)
end

r.ShowConsoleMsg(head .. table.concat(log, "\n") .. "\n" .. tail ..
  "\nNothing is armed. Every patch is muted until StageRig takes over.\n")
